// config.js
module.exports = {
  database: {
    user: 'u325002328_root',
    host: 'srv1494.hstgr.io',
    database: 'u325002328_thepankh',
    password: 'SrjaSky@@9643@@thepankh',
    // user: 'root',
    // host: 'localhost',
    // database: 'thepankh',
    // password: 'SrjaSky@@9643@@thepankh@@artithapa',
  },
  jwtSecret: "thisissecretconversationroomdontinterfere",
  PORT: 3001,
  NODE_ENV: "production",
  SMTP_HOST: "smtp.gmail.com",
  SMTP_PORT: 465,
  SMTP_PASSWORD: "wruyxvzfmnmsjsnl",
  SMTP_MAIL: "skybuildconstructionbazaar@gmail.com",
  JWT_EXPIRES_TIME: "7d",
  COOKIE_EXPIRE: 7,
  JWT_SECRET: "",
  CLOUDINARY_NAME: "dk0o7tdks",
  CLOUDINARY_API_KEY: "341976251712619",
  CLOUDINARY_API_SECRET: "tBAn6Urb3oHKsxFAmgZZGG1j000",
};
